use FIT;

ALTER TABLE dish MODIFY COLUMN name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ingredient MODIFY COLUMN name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user MODIFY COLUMN name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;
